CC=i686-pc-mingw32-gcc
CXX=i686-pc-mingw32-g++
AR=i686-pc-mingw32-ar
LD=i686-pc-mingw32-ld

CPPFLAGS+=-I/media/B2C80DCEC80D91B1/code/fltk1.3/include/
ARCH_FLAGS= -msse -msse2
ARCH_OBJS=arch/yvv.o \
	  arch/sleep.o \
	  arch/system.o


